### ISSUE TITLE
Give each topic a different thumbnail picture

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#19]
Currently, they all have the same picture, and that can be confusing. 
Referring to this picture 
![screen shot 2017-01-05 at 22 08 00](https://cloud.githubusercontent.com/assets/3273659/21699428/969eb246-d393-11e6-85d6-947f4c65984d.png)

**Comment by paulinabustos** [comment]
Debates: 

Official Welcome: https://www.flickr.com/photos/144810968@N02/30059708402/
Global Goals for Local Impact: https://www.flickr.com/photos/144810968@N02/30139615356/
Open Data and Business: https://www.flickr.com/photos/144810968@N02/30059748532/
Open Data and the Data Revolution for Sustainable Development: Opportunities for Joint Action: https://www.flickr.com/photos/144810968@N02/30089654771/
Building an Inclusive Data Revolution: https://www.flickr.com/photos/144810968@N02/29878563790/
Data and Gender: Thinking Critically: https://www.flickr.com/photos/144810968@N02/29545362434/
Open Data and Public Procurement: https://www.flickr.com/photos/144810968@N02/29878583350/
Open Data and National Statistical Offices: Experiences and Opportunities: https://www.flickr.com/photos/144810968@N02/29878609100/
Breaking the Power of Closed: https://www.flickr.com/photos/144810968@N02/29540855004/
Scaling Up and Deepening Open Data's Transformative Impact in Open Government: https://www.flickr.com/photos/144810968@N02/30169580515/
Open Data Charter: Bringing Principles to Practice: https://www.flickr.com/photos/144810968@N02/29531096173/
Open Data and Platforms: https://www.flickr.com/photos/144810968@N02/29531093643/
Open Data and Health: https://www.flickr.com/photos/144810968@N02/30124695106/
Regional Talk - Europe: https://www.flickr.com/photos/144810968@N02/30075224371/
Closing Sessions: https://www.flickr.com/photos/144810968@N02/30169660165/
========
Impact: https://www.flickr.com/photos/144810968@N02/29878494630/in/photostream/
========
Regionals: https://www.flickr.com/photos/144810968@N02/29531605254/in/album-72157673692020400/
=======
Actions: https://www.flickr.com/photos/144810968@N02/30160051935/in/album-72157673692020400/
=======
Community:
https://www.flickr.com/photos/144810968@N02/30169642325/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/29874102740/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/29540855004/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/30134901206/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/29874094490/in/album-72157674884748745/

**Comment by ricalanis** [comment]
@isacoder Can you help me out cropping the images in the community section to fit the height?

**Comment by morchickit** [comment]
@paulinabustos seriously, the pic for the gender session is of two men! It's a bit weird. Can the pics be connected to the session they are on?

**Comment by paulinabustos** [comment]
Thanks for keeping us in check @morchickit! All the pictures inside the pop-up are the ones from the session and the ones in the thumbnails are from people interacting on the open spaces. I tried to mixed different genders and looks. 

@ricalanis  let's use this one for that session in particular. https://www.flickr.com/photos/144810968@N02/29540676533/
