### ISSUE TITLE
Session description is being cut by the "Go to notes" text

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#20]
Make sure the user can see the full description of the session. 
See screenshot:
![screen shot 2017-01-05 at 22 10 12](https://cloud.githubusercontent.com/assets/3273659/21699497/e905a364-d393-11e6-9346-b43c3cac7a41.png)

**Comment by ricalanis** [comment]
Thank you! this was intended to crop 50 words, not characters, from the sched description. Working on this.
