### ISSUE TITLE
Make sure youtube embed is consistent in size

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#21]
Currently the youtube embed feature is in different sizes in different sessions. It seems that the size is dependent on the amount of pictures a session has. 

See here:
![screen shot 2017-01-05 at 22 12 36](https://cloud.githubusercontent.com/assets/3273659/21699583/5aba2548-d394-11e6-8e9f-f2183a8c5e6f.png)

compare to here:
![screen shot 2017-01-05 at 22 12 57](https://cloud.githubusercontent.com/assets/3273659/21699590/5f1579b2-d394-11e6-8cdf-a3e7426467b7.png)

**Comment by paulinabustos** [comment]
@isacoder - Can we review this?
