### ISSUE TITLE
In the buzz section of a session, acknowledge the twitter handle that tweeted the content and add Twitter Icon 

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#22]
Currently, you don't know who that tweet is attributed to...

**Comment by paulinabustos** [comment]
The red square on the left should be a Twitter one. 

![screen shot 2017-01-06 at 9 07 04 am](https://cloud.githubusercontent.com/assets/6033705/21727271/6ab3a706-d3f5-11e6-924e-61b62bdb57be.png)

**Comment by ricalanis** [comment]
Will work on the handle thingy. Need input from @isacoder for twitter icon.

**Comment by ricalanis** [comment]
Handle thing done. Twitter icon is missing.
