### ISSUE TITLE
Add Spanish report notes to the website as well

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#26]
See report here:
https://drive.google.com/drive/folders/0B9TvqAthISVSWFlaTnBVUy1XLUE

**Comment by ricalanis** [comment]
Gonna add a footer note with the spanish report.

**Comment by paulinabustos** [comment]
Still not linked 

![screen shot 2017-01-09 at 9 52 03 pm](https://cloud.githubusercontent.com/assets/6033705/21795298/e235d58e-d6b5-11e6-828d-7de4c3863a24.png)

**Comment by morchickit** [comment]
We don't want a footer with Spanish report, we want to add text to each session.
