### ISSUE TITLE
In the unconference section, link to the OKI discourse forum

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#28]
See here:
https://discuss.okfn.org/c/iodc-unconference

**Comment by paulinabustos** [comment]
![screen shot 2017-01-09 at 9 50 46 pm](https://cloud.githubusercontent.com/assets/6033705/21795268/b95cf7f0-d6b5-11e6-901d-06593661cea2.png)

Still not linked.

**Comment by ricalanis** [comment]
Manually added the tag:
`<a href='https://discuss.okfn.org/c/iodc-unconference'>Go to the unconference forum</a>`
to the json. Will be reflected in next push.
