### ISSUE TITLE
Add social media links

### ISSUE THREAD

**Issue by morchickit** [civica-digital/iodc-report#32]
Facebook - https://www.facebook.com/opendatacon/
Twitter - https://twitter.com/opendatacon
Flickr - https://www.flickr.com/photos/144810968@N02/albums
Youtube - https://www.youtube.com/channel/UC8cKSDSxKSbOnKliM_MhZmQ

**Comment by ricalanis** [comment]
@sofiamoya Can we gather the white svg versions of these?

**Comment by sofiamoya** [comment]
[social-white.zip](https://github.com/civica-digital/iodc-report/files/699702/social-white.zip)

**Comment by ricalanis** [comment]
Where should we put them?

**Comment by ricalanis** [comment]
@sofiamoya @paulinabustos ^
