### ISSUE TITLE
Missing pictures 

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#37]
From Community: https://www.flickr.com/photos/144810968@N02/30059697802/

From Impact: 
https://www.flickr.com/photos/144810968@N02/30139590916/
https://www.flickr.com/photos/144810968@N02/30174284885/
https://www.flickr.com/photos/144810968@N02/30089637181/
https://www.flickr.com/photos/144810968@N02/30089654771/
https://www.flickr.com/photos/144810968@N02/29878563790/
https://www.flickr.com/photos/144810968@N02/29878571890/

From Actions:
https://www.flickr.com/photos/144810968@N02/30123590011/
https://www.flickr.com/photos/144810968@N02/30085170151/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/30134916656/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/29540676533/in/album-72157674884748745/
https://www.flickr.com/photos/144810968@N02/30080898171/in/album-72157673692020400/

**Comment by ricalanis** [comment]
In community we can't switch pictures. In the other sections we can. Changing the ones i can change.

**Comment by ricalanis** [comment]
On it.

**Comment by ricalanis** [comment]
This should be done. @paulinabustos
