### ISSUE TITLE
Icons should be bigger and be centered (horizontally and vertically)

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#39]
<img width="1202" alt="captura de pantalla 2017-01-06 a las 2 29 33 p m" src="https://cloud.githubusercontent.com/assets/6033705/21794597/8ae28ce6-d6b0-11e6-80cd-4605a437f914.png">

**Comment by isacoder** [comment]
is this the correct size of big?
I don't have the original design

![image](https://cloud.githubusercontent.com/assets/10409078/21870337/7a700f1a-d821-11e6-9af3-b9a588f614f8.png)

**Comment by paulinabustos** [comment]
Este es el diseño original que propuso @sofiamoya https://projects.invisionapp.com/d/main#/console/8738643/187172439/preview

@sofiamoya - ¿puedes confirmar el tamaño de los íconos?

**Comment by sofiamoya** [comment]
looks good @isacoder (Y)
