### ISSUE TITLE
Take off the following elements

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#54]
- [ ] Takeaways and The Road Ahead 
- [ ] Pictures from each Debate
- [ ] Description from each Debate
- [ ] Description from Actions
- [ ] Outcomes from Actions
- [ ] Pictures bellow from Community

**Comment by ricalanis** [comment]
Pictures bellow from Community
mind explaining that one?

**Comment by paulinabustos** [comment]
![screen shot 2017-01-11 at 11 41 42 am](https://cloud.githubusercontent.com/assets/6033705/21863613/0bb75b4c-d7f3-11e6-8646-aab6af8a9931.png)

@ricalanis
