### ISSUE TITLE
¿New pop-up design with new content? 

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#64]
@sofiamoya We have new content that we are adding to the pop-up of the design. Do you think we are still being efficient with the space? 

One suggestion is to move the text first and then have the video. 

![screen shot 2017-01-12 at 7 38 57 am](https://cloud.githubusercontent.com/assets/6033705/21896212/6b1c5d60-d89a-11e6-8d84-d8663eab3af2.png)

**Comment by ricalanis** [comment]
I was thinking in a fixed height, scrolleable section with a slightly smaller font.

**Comment by sofiamoya** [comment]
Let's put the paragraph under the title, before speakers, and resize video to fit pop-up width.

**Comment by paulinabustos** [comment]
Like this @sofiamoya ?

![screen shot 2017-01-12 at 2 42 29 pm](https://cloud.githubusercontent.com/assets/6033705/21911383/6765917e-d8d5-11e6-826c-38e2922b70b8.png)

**Comment by paulinabustos** [comment]
@isacoder can we make this changes to the pop-up to accommodate this changes of content?
