### ISSUE TITLE
Main paragraph design 

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#65]
- [x] Change heading to "This Roadmap is the outcome document of the 4th International Open Data Conference"

- [x] Add bullets to each commitment 

- [x] Left justification

- [x] Change the language to the commitments: 

1.       Broaden political commitment to open data principles
2.       Identify and adopt user-centric open standards
3.       Build capacity to produce and effectively use open data
4.       Strengthen networks to address common challenges
5.       Make action on open data movement more evidence-based
6.       Use open data to support the sustainable development agenda
7.       Connect with local communities

- [x] Add a link for the discuss forum ( https://discuss.okfn.org/c/international-open-data-roadmap ) (mockup added) 
![screen shot 2017-01-13 at 11 04 18 am](https://cloud.githubusercontent.com/assets/6033705/21942306/5f5a781c-d981-11e6-9f6d-c4e484fa136e.png)

**Comment by ricalanis** [comment]
Oh, did not see that this actually took that mail into account. my bad.
