### ISSUE TITLE
Change pictures 

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#73]
Impact Area (Accountability) - https://www.flickr.com/photos/144810968@N02/29874160420/in/album-72157674887732025/

Community - https://www.flickr.com/photos/144810968@N02/30125419216/in/album-72157674887732025/

Action Charter - http://farm9.static.flickr.com/8716/30123590011_1788801dab_b.jpg

Action Standard - https://www.flickr.com/photos/144810968@N02/30125288256/in/album-72157673692020400/

**Comment by ricalanis** [comment]
Podemos elegir otra de Impact? el Height to width de esa foto es muy diferente a las demás y se ve rara.

**Comment by ricalanis** [comment]
Check with anon page. May not update.
