### ISSUE TITLE
Add a space of padding between "Download the Report" and "Call to Action"

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#78]
![screen shot 2017-01-15 at 7 30 46 am](https://cloud.githubusercontent.com/assets/6033705/21963736/a0b323da-daf4-11e6-83d1-54b766048e22.png)

**Comment by paulinabustos** [comment]
Me lo imagino así

![screen shot 2017-01-15 at 9 35 38 am](https://cloud.githubusercontent.com/assets/6033705/21964700/ffe1b20c-db05-11e6-8a97-13f7151c1a38.png)

**Comment by ricalanis** [comment]
Done in staging (github.io)

(i cheated and used <brs> for this. shame on me.)
