### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by paulinabustos** [civica-digital/iodc-report#79]
Let's not miss who is going in: 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-69212911-10', 'auto');
  ga('send', 'pageview');

</script>

**Comment by ricalanis** [comment]
Done in staging (github.io)
